sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable
before_install:
  - npm install -g bower
install:
  - npm install
  - bower install
# before_script:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - npm i -g npm@^3
#   - sleep 3 # give xvfb some time to start
notifications:
  email: false
  slack:
    rooms:
      - m-wayteam:id3DFokHndVEGtjOM9fR0DVj#generator-m-services
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
